### ISSUE TITLE
Not alarming after 7.0 Nougat update on Nexus 6P

### ISSUE THREAD

**Issue by aar0nsky** [SheldonNeilson/Android-Alarm-Clock#16]
The app is not firing off alarms after I have updated to 7.0.
I am using the latest version on F-Droid.

**Comment by Forbo** [comment]
Alarms have never functioned on my device. Running a fresh install of 7.1.1 on a Pixel with the latest version of the app from F-Droid.

**Comment by neverpanic** [comment]
Here's a log of the problem:
```
02-22 00:11:00.460  4622  5401 W Intent  : Failure filling in extras
02-22 00:11:00.460  4622  5401 W Intent  : java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = za.co.neilson.alarm.Alarm)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.Parcel.readSerializable(Parcel.java:2630)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.Parcel.readValue(Parcel.java:2416)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:269)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.Bundle.putAll(Bundle.java:226)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.content.Intent.fillIn(Intent.java:8219)
02-22 00:11:00.460  4622  5401 W Intent  : 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:244)
02-22 00:11:00.460  4622  5401 W Intent  : 	at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:205)
02-22 00:11:00.460  4622  5401 W Intent  : 	at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7405)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.app.PendingIntent.send(PendingIntent.java:836)
02-22 00:11:00.460  4622  5401 W Intent  : 	at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3113)
02-22 00:11:00.460  4622  5401 W Intent  : 	at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2546)
02-22 00:11:00.460  4622  5401 W Intent  : 	at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2667)
02-22 00:11:00.460  4622  5401 W Intent  : Caused by: java.lang.ClassNotFoundException: za.co.neilson.alarm.Alarm
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.lang.Class.classForName(Native Method)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.lang.Class.forName(Class.java:400)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.Parcel$2.resolveClass(Parcel.java:2621)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1772)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
02-22 00:11:00.460  4622  5401 W Intent  : 	at android.os.Parcel.readSerializable(Parcel.java:2624)
02-22 00:11:00.460  4622  5401 W Intent  : 	... 12 more
02-22 00:11:00.460  4622  5401 W Intent  : Caused by: java.lang.ClassNotFoundException: Didn't find class "za.co.neilson.alarm.Alarm" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.platform.jar", zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar", zip file "/system/framework/com.cyanogenmod.keyhandler.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
02-22 00:11:00.460  4622  5401 W Intent  : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
02-22 00:11:00.460  4622  5401 W Intent  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-22 00:11:00.460  4622  5401 W Intent  : 	... 22 more
02-22 00:11:00.469  4622 24372 I ActivityManager: START u0 {flg=0x10000000 cmp=za.co.neilson.alarm/.alert.AlarmAlertActivity (has extras)} from uid 10159 on display 0
02-22 00:11:00.515  4622  4697 E Notification: setLatestEventInfo() is deprecated and you should feel deprecated.
02-22 00:11:00.515  4622  4697 E Notification: java.lang.Throwable
02-22 00:11:00.515  4622  4697 E Notification: 	at android.app.Notification.setLatestEventInfo(Notification.java:2083)
02-22 00:11:00.515  4622  4697 E Notification: 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2351)
02-22 00:11:00.515  4622  4697 E Notification: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 00:11:00.515  4622  4697 E Notification: 	at android.os.Looper.loop(Looper.java:154)
02-22 00:11:00.515  4622  4697 E Notification: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-22 00:11:00.515  4622  4697 E Notification: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-22 00:11:00.546  7573  7573 D AndroidRuntime: Shutting down VM
02-22 00:11:00.547  7573  7573 E AndroidRuntime: FATAL EXCEPTION: main
02-22 00:11:00.547  7573  7573 E AndroidRuntime: Process: za.co.neilson.alarm, PID: 7573
02-22 00:11:00.547  7573  7573 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{za.co.neilson.alarm/za.co.neilson.alarm.alert.AlarmAlertActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String za.co.neilson.alarm.Alarm.getAlarmName()' on a null object reference
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6126)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String za.co.neilson.alarm.Alarm.getAlarmName()' on a null object reference
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at za.co.neilson.alarm.alert.AlarmAlertActivity.onCreate(AlarmAlertActivity.java:65)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6679)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
02-22 00:11:00.547  7573  7573 E AndroidRuntime: 	... 9 more
02-22 00:11:00.549  4622 10876 W ActivityManager:   Force finishing activity za.co.neilson.alarm/.alert.AlarmAlertActivity
02-22 00:11:00.608  4622 11198 I OpenGLRenderer: Initialized EGL, version 1.4
02-22 00:11:00.608  4622 11198 D OpenGLRenderer: Swap behavior 1
02-22 00:11:01.054  4622  4697 W ActivityManager: Activity pause timeout for ActivityRecord{303f215 u0 za.co.neilson.alarm/.alert.AlarmAlertActivity t421 f}
```

**Comment by neverpanic** [comment]
Seems like this might be an instance of https://code.google.com/p/android/issues/detail?id=6822, and an easy workaround might be passing the extra wrapped in a Bundle because those seem to be unwrapped lazily inside the process that has the correct classpath set (cf. comment 8: https://code.google.com/p/android/issues/detail?id=6822#c8).

I haven't tried it, but maybe
```java
Bundle bundle = new Bundle();
bundle.putSerializable("alarm", alarm);
intent.putExtra("alarm", bundle);
```
where the intents are created and
```java
Bundle bundle = this.getIntent().getBundleExtra("alarm");
alarm = bundle.getSerializable("alarm");
```
where they are used might work.

**Comment by jeffkap** [comment]
My phone is a Galaxy S7 on AT&T.  The alarm clock no longer works after my upgrade to 7.0 Nougat.  Is the original author of this app still around?  I really appreciate the app.  I'll pay a bounty for a successful bug fix.  

Is there a good alternative app?

**Comment by neverpanic** [comment]
I tested this modification locally and it fixes the issue for me. Unfortunately I broke some other things while doing that, so until I have those fixed, I cannot send a PR.

**Comment by SheldonNeilson** [comment]
Thanks for the feedback. Unfortunately I am not able to dedicate much time to this right away. If someone is able to implement and test this fix I'll gladly pull it.

**Comment by lyn1337** [comment]
confirming.

**Comment by Simfa11** [comment]
Please how do we get previous versions...the updated one is not working on android 6.0

**Comment by ngost** [comment]
i modifyed and running in Nouget, galaxy A7
i modify this..
Alarm.java
------------
Intent myIntent = new Intent(context, AlarmAlertBroadcastReciever.class);
Bundle bundle = new Bundle();
bundle.putSerializable("alarm",this);
myIntent.putExtra("bundle", bundle);
------------
