### ISSUE TITLE
It has crash when alarm is ringing.

### ISSUE THREAD

**Issue by cuibomb0204** [SheldonNeilson/Android-Alarm-Clock#17]
In the AlarmAlertActivity class, given the code below:

```
Bundle bundle = this.getIntent().getExtras();
alarm = (Alarm) bundle.getSerializable("alarm");
```
This crash is due to the null value of alarm 

Here's a log of the problem:

FATAL EXCEPTION: main
                                                                     Process: za.co.neilson.alarm, PID: 26252
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{za.co.neilson.alarm/za.co.neilson.alarm.alert.AlarmAlertActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String za.co.neilson.alarm.Alarm.getAlarmName()' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String za.co.neilson.alarm.Alarm.getAlarmName()' on a null object reference
                                                                         **# at za.co.neilson.alarm.alert.AlarmAlertActivity.onCreate(AlarmAlertActivity.java:67)**
                                                                         at android.app.Activity.performCreate(Activity.java:6942)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by i-keyword** [comment]
Please pay 60$ for me, i fixed it. Very sad. fuck you
